# https://vitepress.dev/reference/default-theme-config
nav:
  - text: 主页
    link: /
  - text: 快速入门
    link: /learn/
    activeMatch: /learn/
  - text: 参考文档
    link: /guide/
    activeMatch: /guide/
  - text: WriteUp
    link: /wp/
    activeMatch: /wp/
    # items:
    #   - text: '2024'
    #     link: /wp/2024/

sidebar:
  '/learn/':
    - text: 写在前面
      link: /learn/
    - text: 开始
      link: /learn/start

    - text: 各方向入门介绍
      items:
      - text: Web 网络攻防
        link: /learn/web
      - text: Crypto 密码学
        link: /learn/crypto
      - text: Reverse 逆向工程
        link: /learn/reverse
      - text: Pwn 二进制安全
        link: /learn/pwn
      - text: Misc 杂项
        link: /learn/misc

    - text: 参考教程
      items:
      - text: VSCode Python 环境配置
        link: /learn/vscode-python
      - text: 获取 Linux 发行版
        link: /learn/get-linux
      - text: 切换软件源
        link: /learn/change-software-source
      - text: Pwn 环境配置
        link: /learn/configure-pwn
      - text: Netcat 使用指南
        link: /learn/nc

    - text: Q&A
      link: /learn/qa

  '/guide/2024/':
    - text: 赛事信息
      link: /guide/2024/
    - text: 解题参考
      items:
        - text: Week 1
          link: /guide/2024/week1
        - text: Week 2
          link: /guide/2024/week2

  '/wp/2024/':
    - text: Week 1
      items:
        - text: Web
          collapsed: true
          items:
            - text: headach3
              link: /wp/2024/week1/web/headach3
            - text: 智械危机
              link: /wp/2024/week1/web/zhixieweiji
            - text: 会赢吗？
              link: /wp/2024/week1/web/huiyingma
            - text: PangBai 过家家（1）
              link: /wp/2024/week1/web/pangbai1
            - text: 谢谢皮蛋
              link: /wp/2024/week1/web/xiexiepidan
        - text: Crypto
          collapsed: true
          items:
            - text: xor
              link: /wp/2024/week1/crypto/xor
            - text: Base
              link: /wp/2024/week1/crypto/base
            - text: Strange King
              link: /wp/2024/week1/crypto/strange-king
            - text: 一眼秒了
              link: /wp/2024/week1/crypto/yiyanmiaole
        - text: Pwn
          collapsed: true
          items:
            - text: Real Login
              link: /wp/2024/week1/pwn/real-login
            - text: Game
              link: /wp/2024/week1/pwn/game
            - text: Overwrite
              link: /wp/2024/week1/pwn/overwrite
            - text: Gdb
              link: /wp/2024/week1/pwn/gdb
        - text: Misc
          collapsed: true
          items:
            - text: Labyrinth
              link: /wp/2024/week1/misc/labyrinth
            - text: decompress（校内赛道）
              link: /wp/2024/week1/misc/decompress
            - text: decompress（公开赛道）
              link: /wp/2024/week1/misc/decompress-public
            - text: WhereIsFlag
              link: /wp/2024/week1/misc/whereisflag
            - text: pleasingMusic
              link: /wp/2024/week1/misc/pleasingmusic
            - text: 兑换码
              link: /wp/2024/week1/misc/duihuanma
