# https://vitepress.dev/reference/default-theme-config
nav:
  - text: 主页
    link: /
  - text: 快速入门
    link: /learn/
    activeMatch: /learn/
  - text: 参考文档
    link: /guide/
    activeMatch: /guide/
  - text: WriteUp
    link: /wp/
    activeMatch: /wp/
    # items:
    #   - text: '2024'
    #     link: /wp/2024/

sidebar:
  '/learn/':
    - text: 写在前面
      link: /learn/
    - text: 各方向入门介绍
      items:
      - text: Web 网络攻防
        link: /learn/web
      - text: Crypto 密码学
        link: /learn/crypto
      - text: Reverse 逆向工程
        link: /learn/reverse
      - text: Pwn 二进制安全
        link: /learn/pwn
      - text: Misc 杂项
        link: /learn/misc
    - text: Q&A
      link: /learn/qa

  '/guide/2024/':
    - text: 赛事信息
      link: /guide/2024/
    - text: Week 1
      collapsed: false
      items:
        - text: Web
          link: /guide/2024/week1/web

  '/wp/2024/':
    - text: Week 1
      items:
        - text: Web
          collapsed: false
          items:
            - text: Example
              link: /wp/2024/week1/web/example