# https://vitepress.dev/reference/default-theme-config
nav:
  - text: 主页
    link: /
  - text: 快速入门
    link: /learn/
    activeMatch: /learn/
  - text: 参考文档
    link: /guide/
    activeMatch: /guide/
  - text: WriteUp
    link: /wp/
    activeMatch: /wp/
    # items:
    #   - text: '2024'
    #     link: /wp/2024/

sidebar:
  '/learn/':
    - text: 写在前面
      link: /learn/
    - text: 开始
      link: /learn/start

    - text: 各方向入门介绍
      items:
      - text: Web 网络攻防
        link: /learn/web
      - text: Crypto 密码学
        link: /learn/crypto
      - text: Reverse 逆向工程
        link: /learn/reverse
      - text: Pwn 二进制安全
        link: /learn/pwn
      - text: Misc 杂项
        link: /learn/misc

    - text: 参考教程
      items:
      - text: VSCode Python 环境配置
        link: /learn/vscode-python
      - text: 获取 Linux 发行版
        link: /learn/get-linux
      - text: 切换软件源
        link: /learn/change-software-source
      - text: Pwn 环境配置
        link: /learn/configure-pwn
      - text: Netcat 使用指南
        link: /learn/nc

    - text: Q&A
      link: /learn/qa

  '/guide/2024/':
    - text: 赛事信息
      link: /guide/2024/
    - text: 解题参考
      items:
        - text: Week 1
          link: /guide/2024/week1
        - text: Week 2
          link: /guide/2024/week2
        - text: Week 3
          link: /guide/2024/week3
        - text: Week 4
          link: /guide/2024/week4

  '/wp/2024/':
    - text: Week 1
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: Real Login
              link: /wp/2024/week1/pwn/real-login
            - text: Game
              link: /wp/2024/week1/pwn/game
            - text: Overwrite
              link: /wp/2024/week1/pwn/overwrite
            - text: Gdb
              link: /wp/2024/week1/pwn/gdb
        - text: Reverse
          collapsed: true
          items:
            - text: begin
              link: /wp/2024/week1/reverse/begin
            - text: base64
              link: /wp/2024/week1/reverse/base64
            - text: ezAndroidStudy
              link: /wp/2024/week1/reverse/ezandroidstudy
            - text: Simple_encryption
              link: /wp/2024/week1/reverse/simple-encryption
            - text: ez_debug
              link: /wp/2024/week1/reverse/ez-debug
        - text: Web
          collapsed: true
          items:
            - text: headach3
              link: /wp/2024/week1/web/headach3
            - text: 会赢吗？
              link: /wp/2024/week1/web/huiyingma
            - text: 智械危机
              link: /wp/2024/week1/web/zhixieweiji
            - text: PangBai 过家家（1）
              link: /wp/2024/week1/web/pangbai1
            - text: 谢谢皮蛋
              link: /wp/2024/week1/web/xiexiepidan
        - text: Crypto
          collapsed: true
          items:
            - text: xor
              link: /wp/2024/week1/crypto/xor
            - text: Base
              link: /wp/2024/week1/crypto/base
            - text: 一眼秒了
              link: /wp/2024/week1/crypto/yiyanmiaole
            - text: Strange King
              link: /wp/2024/week1/crypto/strange-king
        - text: Misc
          collapsed: true
          items:
            - text: decompress
              link: /wp/2024/week1/misc/decompress
            - text: WhereIsFlag
              link: /wp/2024/week1/misc/whereisflag
            - text: pleasingMusic
              link: /wp/2024/week1/misc/pleasingmusic
            - text: Labyrinth
              link: /wp/2024/week1/misc/labyrinth
            - text: 兑换码
              link: /wp/2024/week1/misc/duihuanma
    - text: Week 2
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: EZ_fmt
              link: /wp/2024/week2/pwn/ez-fmt
            - text: Inverted World
              link: /wp/2024/week2/pwn/inverted-world
            - text: Bad Asm
              link: /wp/2024/week2/pwn/bad-asm
            - text: ez_game
              link: /wp/2024/week2/pwn/ez-game
            - text: My_GBC!!!!!
              link: /wp/2024/week2/pwn/my-gbc
        - text: Reverse
          collapsed: true
          items:
            - text: Pangbai 泰拉记（1）
              link: /wp/2024/week2/reverse/pangbai-terra1
            - text: Ezencypt
              link: /wp/2024/week2/reverse/ezencypt
            - text: UPX
              link: /wp/2024/week2/reverse/upx
            - text: Ptrace
              link: /wp/2024/week2/reverse/ptrace
            - text: drink_tea
              link: /wp/2024/week2/reverse/drink_tea
            - text: Dirty_flowers
              link: /wp/2024/week2/reverse/dirty-flowers
        - text: Web
          collapsed: true
          items:
            - text: 你能在一秒内打出八句英文吗
              link: /wp/2024/week2/web/bajuyingwen
            - text: 遗失的拉链
              link: /wp/2024/week2/web/yishidelalian
            - text: 复读机
              link: /wp/2024/week2/web/fuduji
            - text: PangBai 过家家（2）
              link: /wp/2024/week2/web/pangbai2
            - text: 谢谢皮蛋 plus
              link: /wp/2024/week2/web/pidan-plus
        - text: Crypto
          collapsed: true
          items:
            - text: 这是几次方？ 疑惑！
              link: /wp/2024/week2/crypto/jicifang
            - text: Since you konw something
              link: /wp/2024/week2/crypto/since-you-know-something
            - text: just one and more than two
              link: /wp/2024/week2/crypto/just-one-and-more-than-two
            - text: 茶里茶气
              link: /wp/2024/week2/crypto/chalichaqi
        - text: Misc
          collapsed: true
          items:
            - text: wireshark_checkin
              link: /wp/2024/week2/misc/wireshark-checkin
            - text: wireshark_secret
              link: /wp/2024/week2/misc/wireshark-secret
            - text: 你也玩原神吗？
              link: /wp/2024/week2/misc/genshin
            - text: 字里行间的秘密
              link: /wp/2024/week2/misc/zilihangjian
            - text: 热心助人的小明同学
              link: /wp/2024/week2/misc/xiaoming1
            - text: 用溯流仪见证伏特台风
              link: /wp/2024/week2/misc/futetaifeng
            - text: Herta's Study
              link: /wp/2024/week2/misc/herta
    - text: Week 3
      items:
        - text: Pwn
          collapsed: false
          items:
            - text: 不思議なscanf
              link: /wp/2024/week3/pwn/scanf
            - text: One Last B1te
              link: /wp/2024/week3/pwn/one-last-b1te
            - text: ezcanary
              link: /wp/2024/week3/pwn/ezcanary
            - text: Easy_Shellcode
              link: /wp/2024/week3/pwn/easy-shellcode
        - text: Reverse
          collapsed: false
          items:
            - text: 011vm
              link: /wp/2024/week3/reverse/011vm
            - text: simpleAndroid
              link: /wp/2024/week3/reverse/simpleandroid
            - text: SMc_math
              link: /wp/2024/week3/reverse/smc-math
            - text: flowering_shrubs
              link: /wp/2024/week3/reverse/flowering-shrubs
            - text: SecertsOfKawaii
              link: /wp/2024/week3/reverse/secrets-of-kawaii
            - text: PangBai 过家家（3）
              link: /wp/2024/week3/reverse/pangbai3
            - text: 取啥名好呢
              link: /wp/2024/week3/reverse/qushaming
        - text: Web
          collapsed: false
          items:
            - text: 臭皮的计算器
              link: /wp/2024/week3/web/jisuanqi
            - text: 臭皮踩踩背
              link: /wp/2024/week3/web/caicaibei
            - text: 这照片是你吗
              link: /wp/2024/week3/web/zhaopian
            - text: Include_Me
              link: /wp/2024/week3/web/include-me
            - text: blindsql1
              link: /wp/2024/week3/web/blindsql1
        - text: Crypto
          collapsed: false
          items:
            - text: 没e这能玩？
              link: /wp/2024/week3/crypto/noenoplay
            - text: 故事新编1
              link: /wp/2024/week3/crypto/gushixinbian1
            - text: 故事新编2
              link: /wp/2024/week3/crypto/gushixinbian2
            - text: 不用谢喵
              link: /wp/2024/week3/crypto/buyongxiemiao
            - text: 两个黄鹂鸣翠柳
              link: /wp/2024/week3/crypto/lianggehuangli
        - text: Misc
          collapsed: false
          items:
            - text: OSINT-MASTER
              link: /wp/2024/week3/misc/osint-master
            - text: BGM坏了吗？
              link: /wp/2024/week3/misc/bgm-broken
            - text: AmazingGame
              link: /wp/2024/week3/misc/amazinggame
            - text: ez_jail
              link: /wp/2024/week3/misc/ez-jail
